import { useEffect, useMemo, useState, type FormEvent } from "react";

type User = { username: string; role: "user" | "admin"; createdAt: string };
type State = { registration?: { displayName: string }; modules: Array<{ id: string; name: string; displayName: string; blueprintId: string; runtimeAttributes: Record<string, unknown> }>; blueprints: Array<{ blueprintId: string; displayName?: string; inputs?: Record<string, number>; buildTicks?: number; ticks?: number }>; inventory: Record<string, number>; constructionJobs: Array<{ id: string; moduleName: string; blueprintId: string; remainingBuildTicks: number; totalBuildTicks: number }>; power: { powerConsumedTicks: number } };
type Command = { id: string; title: string; group: string; description: string; method: "GET" | "POST" | "DELETE"; path: string; fields?: string[] };

const emptyState: State = { modules: [], blueprints: [], inventory: {}, constructionJobs: [], power: { powerConsumedTicks: 0 } };
const commands: Command[] = [
  ["status", "Habitat status", "Habitat", "Inspect registration and system counts.", "GET", "/commands/status"],
  ["register", "Register habitat", "Habitat", "Create a local habitat registration.", "POST", "/commands/register", "name"],
  ["link", "Link habitat", "Habitat", "Link this workspace to a remote habitat.", "POST", "/commands/link", "id"],
  ["solar", "Solar status", "Solar & Power", "Inspect live solar conditions.", "GET", "/commands/solar/status"],
  ["power", "Power overview", "Solar & Power", "Summarize power draw.", "GET", "/commands/power/overview"],
  ["tick", "Run ticks", "Simulation", "Advance the habitat simulation.", "POST", "/commands/tick", "count"],
  ["blueprints", "Refresh blueprints", "Blueprints", "Load the blueprint catalog.", "GET", "/commands/blueprint/list"],
  ["resources", "List resources", "Resources", "Load the resource catalog.", "GET", "/commands/resource/list"],
  ["inventory", "Set inventory", "Inventory", "Set a resource quantity.", "POST", "/commands/inventory/set", "resourceId,amount"],
  ["construct", "Construct module", "Construction", "Start construction from a blueprint.", "POST", "/commands/construct", "blueprintId,displayName"],
  ["modules", "List modules", "Modules", "Inspect all modules.", "GET", "/commands/module/list"],
  ["normalize", "Normalize module names", "Modules", "Repair module IDs and connections.", "POST", "/commands/module/normalize-names"],
  ["force", "Force construct", "Admin", "Force-create a module without gameplay checks.", "POST", "/commands/debug/construct", "blueprintId"],
  ["recharge", "Recharge batteries", "Admin", "Fill all battery modules.", "POST", "/commands/debug/recharge-batteries"],
  ["drain", "Battery drain", "Admin", "Inspect battery drain calculations.", "GET", "/commands/debug/battery-drain"],
  ["sqlite", "Rebuild SQLite", "Admin", "Rebuild local SQLite state.", "POST", "/commands/storage/sqlite"],
  ["restore", "Restore backup", "Admin", "Restore the local data backup.", "POST", "/commands/storage/restore"],
].map(([id, title, group, description, method, path, fields]) => ({ id, title, group, description, method: method as Command["method"], path, fields: fields ? fields.split(",") : undefined }));

async function api<T>(path: string, init: RequestInit = {}): Promise<T> { const response = await fetch(path, { ...init, headers: { "content-type": "application/json", ...(init.headers ?? {}) } }); const text = await response.text(); let body: unknown = null; try { body = text ? JSON.parse(text) : null; } catch { body = text; } if (!response.ok) throw new Error(typeof body === "object" && body && "message" in body ? String((body as { message: unknown }).message) : String(body || `Request failed (${response.status})`)); return body as T; }
const label = (value: string) => value.replace(/([A-Z])/g, " $1").replace(/[-_]/g, " ").replace(/^./, (c) => c.toUpperCase());
const output = (value: unknown): string => { if (value == null) return "No response data."; if (typeof value !== "object") return String(value); if (Array.isArray(value)) return value.map((item) => `• ${output(item)}`).join("\n"); return Object.entries(value as Record<string, unknown>).map(([key, item]) => `${label(key)}: ${typeof item === "object" ? `\n${output(item)}` : String(item ?? "—")}`).join("\n"); };
const status = (module: State["modules"][number]) => String(module.runtimeAttributes.state ?? module.runtimeAttributes.status ?? "offline");
function Icon({ name }: { name: string }) { const paths: Record<string, string> = { Overview: "M3 10 12 3l9 7v10a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1V10Z", Habitat: "M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18Zm0 4v5l3 2", Modules: "M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z", Construction: "M4 20V10l8-6 8 6v10M8 20v-5h8v5", Inventory: "M4 5h16v14H4zM8 9h8M8 13h8M8 17h5", Blueprints: "M7 3h10v18H7zM7 7H4v14h10M10 11h4M10 15h4", Resources: "M12 3v18M3 12h18M5 5l14 14M19 5 5 19", "Solar & Power": "M13 2 4 14h7l-1 8 10-12h-7l0-8Z", Settings: "M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8Zm0-5v3m0 12v3m9-9h-3M6 12H3m15.4-6.4-2.1 2.1M7.7 16.3l-2.1 2.1m12.8 0-2.1-2.1M7.7 7.7 5.6 5.6" }; return <svg className="ui-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name] ?? paths.Overview} /></svg>; }

export function App() {
  const [state, setState] = useState<State>(emptyState); const [user, setUser] = useState<User | null>(null); const [view, setView] = useState("Overview"); const [drawer, setDrawer] = useState(false); const [account, setAccount] = useState(false); const [authOpen, setAuthOpen] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const refresh = async () => { setLoading(true); try { const [session, next] = await Promise.all([api<{ user: User | null }>("/auth/me"), api<State>("/state")]); setUser(session.user); setState(next); setError(""); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setLoading(false); } };
  useEffect(() => { void refresh(); }, []);
  useEffect(() => { if (view !== "Admin" || user?.role !== "admin") return; const timer = window.setTimeout(() => { const empty = [...document.querySelectorAll<HTMLElement>(".empty-state")].find((node) => node.textContent?.includes("Use the command drawer")); if (!empty) return; empty.innerHTML = `<div class="admin-action-grid"><button class="secondary" data-admin-action="drain">Battery drain</button><button class="secondary" data-admin-action="recharge">Recharge batteries</button><button class="secondary" data-admin-action="sqlite">Rebuild SQLite</button><button class="danger" data-admin-action="restore">Restore backup</button><button class="primary" data-admin-action="force">Force construct</button></div><div class="admin-action-result" aria-live="polite"></div>`; const result = empty.querySelector<HTMLElement>(".admin-action-result")!; empty.querySelectorAll<HTMLButtonElement>("[data-admin-action]").forEach((button) => button.addEventListener("click", async () => { const action = button.dataset.adminAction!; const blueprintId = action === "force" ? window.prompt("Blueprint ID to force construct:") : null; if (action === "force" && !blueprintId) return; const paths: Record<string, [string, string]> = { drain: ["GET", "/commands/debug/battery-drain"], recharge: ["POST", "/commands/debug/recharge-batteries"], sqlite: ["POST", "/commands/storage/sqlite"], restore: ["POST", "/commands/storage/restore"], force: ["POST", "/commands/debug/construct"] }; const [method, path] = paths[action]; try { const data = await api(path, { method, body: blueprintId ? JSON.stringify({ blueprintId }) : undefined }); result.textContent = output(data); await refresh(); } catch (error) { result.textContent = error instanceof Error ? error.message : String(error); } })); }, 0); return () => window.clearTimeout(timer); }, [view, user]);
  useEffect(() => { const close = (event: PointerEvent) => { if (!(event.target instanceof Element) || !event.target.closest(".account-wrap")) setAccount(false); }; const ripple = (event: PointerEvent) => { const target = event.target instanceof Element ? event.target.closest<HTMLElement>("button, .command-item, .nav-item, .list-row") : null; if (!target) return; const bounds = target.getBoundingClientRect(); const pulse = document.createElement("span"); pulse.className = "click-ripple"; pulse.style.left = `${event.clientX - bounds.left}px`; pulse.style.top = `${event.clientY - bounds.top}px`; target.append(pulse); pulse.addEventListener("animationend", () => pulse.remove(), { once: true }); }; document.addEventListener("pointerdown", close); document.addEventListener("pointerdown", ripple); return () => { document.removeEventListener("pointerdown", close); document.removeEventListener("pointerdown", ripple); }; }, []);
  const nav = ["Overview", "Habitat", "Modules", "Construction", "Inventory", "Blueprints", "Resources", "Solar & Power", "Settings"];
  const admin = view === "Admin" && user?.role === "admin";
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark"><Icon name="Overview" /></span><span>Habitat</span></div><div className="workspace"><span className="workspace-avatar">{(state.registration?.displayName ?? "H")[0]}</span><span>{state.registration?.displayName ?? "Local workspace"}</span><span className="chevron">⌄</span></div><nav>{nav.map((item) => <button key={item} className={`nav-item ${view === item ? "active" : ""}`} onClick={() => setView(item)}><span className="nav-icon"><Icon name={item} /></span>{item}</button>)}</nav><div className="sidebar-foot"><span className={`status-dot ${error ? "offline" : ""}`}></span><span>{error ? "API unavailable" : "Local API online"}</span></div></aside><main className="main"><header className="topbar"><div className="crumb"><span>Habitat</span><span className="slash">/</span><strong>{view}</strong></div><div className="top-actions"><button className="search-button" onClick={() => setDrawer(true)}><span className="search-icon"><Icon name="Resources" /></span> Search commands <kbd>⌘ K</kbd></button><button className="icon-button" onClick={() => void refresh()} aria-label="Refresh"><Icon name="Resources" /></button><div className="account-wrap"><button className="account-button" onClick={() => setAccount(!account)}><span className="profile">{(user?.username ?? "H")[0].toUpperCase()}</span><span className="account-name">{user?.username ?? "Sign in"}</span>{user?.role === "admin" && <span className="admin-badge">ADMIN</span>}</button>{account && <div className="account-menu"><strong>{user?.username ?? "Guest"}</strong>{user ? <><span>{user.role}</span>{user.role === "admin" && <button onClick={() => { setView("Admin"); setAccount(false); }}>Admin panel</button>}<button onClick={async () => { await api("/auth/logout", { method: "POST" }); setUser(null); setAccount(false); }}>Sign out</button></> : <button onClick={() => { setAuthOpen(true); setAccount(false); }}>Sign up / sign in</button>}</div>}</div></div></header><div className="content">{loading ? <div className="empty-state">Loading Habitat…</div> : admin ? <AdminPanel onRefresh={refresh} /> : <Page view={view} state={state} onCommand={(command) => setDrawer(false)} />}</div></main>{drawer && <CommandDrawer user={user} onClose={() => setDrawer(false)} onDone={refresh} />}{authOpen && <AuthModal onClose={() => setAuthOpen(false)} onUser={(next) => { setUser(next); setAuthOpen(false); void refresh(); }} />}</div>;
}

function Page({ view, state, onCommand }: { view: string; state: State; onCommand: (command: Command) => void }) { const registered = Boolean(state.registration); if (view === "Blueprints") return <Blueprints state={state} />; const title = view === "Overview" ? `Good morning${registered ? `, ${state.registration?.displayName}` : ""}` : view; const online = state.modules.filter((m) => ["online", "active", "idle"].includes(status(m))).length; const content = view === "Overview" ? <><div className="metrics"><Metric label="Modules online" value={`${online}/${state.modules.length}`} /><Metric label="Power consumed" value={state.power.powerConsumedTicks} /><Metric label="Inventory lines" value={Object.keys(state.inventory).length} /><Metric label="Construction" value={state.constructionJobs.length} /></div><div className="list-row"><div><strong>Module activity</strong><span className="subtle">{state.modules.length ? `${online} operational modules` : "No modules yet"}</span></div></div></> : <div className="empty-state">Use the command drawer to operate {view.toLowerCase()}.</div>; return <><div className="page-title"><div><div className="eyebrow">HABITAT CONTROL</div><h1>{title}</h1><p className="muted">{view === "Overview" ? "Your habitat at a glance." : "Habitat operations."}</p></div></div><section className="card"><div className="card-head"><div><div className="eyebrow">LIVE STATUS</div><h2>{view}</h2></div></div>{content}</section></>; }
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="metric"><div className="metric-label">{label}</div><div className="metric-value">{String(value)}</div><div className="metric-detail">Current habitat data</div></div>; }
function Blueprints({ state }: { state: State }) { return <><div className="page-title"><div><div className="eyebrow">BLUEPRINT CATALOG</div><h1>Blueprints</h1><p className="muted">See exactly what each design needs before construction.</p></div></div><section className="card">{state.blueprints.length ? state.blueprints.map((blueprint) => <div className="blueprint-row" key={blueprint.blueprintId}><div className="blueprint-title"><strong>{blueprint.displayName ?? blueprint.blueprintId}</strong><span className="subtle">{blueprint.blueprintId} · {blueprint.buildTicks ?? blueprint.ticks ?? "—"} ticks</span></div><div className="materials"><span className="materials-label">Materials</span>{Object.entries(blueprint.inputs ?? {}).filter(([, amount]) => amount > 0).map(([id, amount]) => <span className="material-chip" key={id}>{label(id)} × {amount.toLocaleString()}</span>)}{!Object.keys(blueprint.inputs ?? {}).length && <span className="subtle">None required</span>}</div></div>) : <div className="empty-state">Catalog is empty. Refresh it from the command drawer.</div>}</section></>; }
function AdminPanel({ onRefresh }: { onRefresh: () => Promise<void> }) { const [users, setUsers] = useState<User[]>([]); const [error, setError] = useState(""); useEffect(() => { void api<User[]>("/admin/users").then(setUsers).catch((e) => setError(e.message)); }, []); return <><div className="page-title"><div><div className="eyebrow">ADMINISTRATION</div><h1>Admin panel</h1><p className="muted">Manage users and privileged diagnostics.</p></div></div><section className="card"><div className="card-head"><div><div className="eyebrow">ACCESS CONTROL</div><h2>Users</h2></div></div>{error ? <div className="empty-state">{error}</div> : users.map((item) => <div className="setting-row" key={item.username}><div><strong>{item.username}</strong><span className="subtle">Joined {new Date(item.createdAt).toLocaleString()}</span></div><select value={item.role} onChange={async (event) => { await api(`/admin/users/${encodeURIComponent(item.username)}/role`, { method: "POST", body: JSON.stringify({ role: event.target.value }) }); setUsers(users.map((u) => u.username === item.username ? { ...u, role: event.target.value as User["role"] } : u)); }}><option value="user">User</option><option value="admin">Admin</option></select></div>)}</section><section className="card"><div className="card-head"><div><div className="eyebrow">PRIVILEGED TOOLS</div><h2>Diagnostics</h2></div></div><div className="empty-state">Use the command drawer to run admin diagnostics. <button className="secondary" onClick={() => void onRefresh()}>Refresh</button></div></section></>; }
function AuthModal({ onClose, onUser }: { onClose: () => void; onUser: (user: User) => void }) { const [username, setUsername] = useState(""); const [error, setError] = useState(""); const submit = async (event: FormEvent) => { event.preventDefault(); try { let result: { user: User }; try { result = await api("/auth/login", { method: "POST", body: JSON.stringify({ username }) }); } catch { result = await api("/auth/signup", { method: "POST", body: JSON.stringify({ username }) }); } onUser(result.user); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } }; return <div className="modal-backdrop" onClick={(e) => e.currentTarget === e.target && onClose()}><form className="modal" onSubmit={submit}><div className="eyebrow">HABITAT ACCOUNT</div><h2>Choose a username</h2><p className="muted">No password required. This identifies your local session.</p><label>Username<input value={username} onChange={(e) => setUsername(e.target.value)} minLength={2} maxLength={32} required placeholder="user" /></label>{error && <p className="error-text">{error}</p>}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary">Continue</button></div></form></div>; }
function CommandDrawer({ user, onClose, onDone }: { user: User | null; onClose: () => void; onDone: () => Promise<void> }) { const [query, setQuery] = useState(""); const [selected, setSelected] = useState<Command | null>(null); const visible = useMemo(() => commands.filter((command) => (user?.role === "admin" || command.group !== "Admin") && `${command.title} ${command.description}`.toLowerCase().includes(query.toLowerCase())), [query, user]); return <><div className="drawer-backdrop" onClick={onClose}></div><aside className="command-drawer"><div className="drawer-head"><div><div className="eyebrow">COMMAND CENTER</div><h2>Run a command</h2></div><button className="icon-button" onClick={onClose}>×</button></div><input className="command-search" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search commands…" autoFocus /><div className="command-list">{visible.map((command) => <button className="command-item" key={command.id} onClick={() => setSelected(command)}><span className="command-symbol">◇</span><span><strong>{command.title}</strong><small>{command.group} · {command.description}</small></span><span>›</span></button>)}</div></aside>{selected && <CommandModal command={selected} onClose={() => setSelected(null)} onDone={onDone} />}</>; }
function CommandModal({ command, onClose, onDone }: { command: Command; onClose: () => void; onDone: () => Promise<void> }) { const [values, setValues] = useState<Record<string, string>>({}); const [result, setResult] = useState(""); const submit = async (event: FormEvent) => { event.preventDefault(); let path = command.path; for (const field of command.fields ?? []) if (path.includes(`{${field}}`)) { path = path.replace(`{${field}}`, encodeURIComponent(values[field] ?? "")); } const body = Object.fromEntries(Object.entries(values).filter(([key]) => !command.path.includes(`{${key}}`))); try { const data = await api(path, { method: command.method, body: command.method === "POST" ? JSON.stringify(body) : undefined }); setResult(output(data)); await onDone(); } catch (e) { setResult(e instanceof Error ? e.message : String(e)); } }; return <div className="modal-backdrop" onClick={(e) => e.currentTarget === e.target && onClose()}><form className="modal" onSubmit={submit}><div className="eyebrow">{command.group}</div><h2>{command.title}</h2><p className="muted">{command.description}</p>{(command.fields ?? []).map((field) => <label key={field}>{label(field)}<input value={values[field] ?? ""} onChange={(e) => setValues({ ...values, [field]: e.target.value })} required /></label>)}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Close</button><button className="primary">Run command</button></div>{result && <pre className="result">{result}</pre>}</form></div>; }
